"""Write CPython's `str.isprintable()` as a Rust range table, for Python `repr()` in ollaya-decision.

    uv run python -m ollaya_convert.pyrepr_tables

Von renders structured state and criteria with Python `str()`, which quotes nested strings with
`repr()`. `repr()` escapes every character `Py_UNICODE_ISPRINTABLE` rejects (general categories Cc,
Cf, Cs, Co, Cn, Zl, Zp and Zs except the space). Rust's `char` API does not expose that set, and its
Unicode version differs from CPython's, so the set comes from this interpreter:

    crates/ollaya-decision/src/printable.rs   PRINTABLE: sorted, disjoint (first, last) ranges
"""
import os
import sys
import unicodedata

CRATE = os.path.join(os.path.dirname(__file__), "..", "..", "crates", "ollaya-decision")


def printable_ranges():
    out, start = [], None
    for cp in range(sys.maxunicode + 1):
        if chr(cp).isprintable():
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, sys.maxunicode))
    return out


def main():
    ranges = printable_ranges()
    lines = [
        "//! Data read from CPython. Generated by `python -m ollaya_convert.pyrepr_tables`; do not edit.",
        "//!",
        "//! CPython %s, Unicode %s: the code points `str.isprintable()` accepts, which `repr()` keeps"
        % (sys.version.split()[0], unicodedata.unidata_version),
        "//! as they are. Every other code point is escaped.",
        "",
        "/// Printable code points as sorted, disjoint `(first, last)` ranges.",
        "#[rustfmt::skip]",
        "pub(crate) static PRINTABLE: &[(u32, u32)] = &[",
    ]
    row = []
    for lo, hi in ranges:
        row.append("(0x%04X, 0x%04X)," % (lo, hi))
        if len(row) == 5:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    path = os.path.normpath(os.path.join(CRATE, "src", "printable.rs"))
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %d ranges" % (path, len(ranges)))


if __name__ == "__main__":
    main()
