//! Raw bindings to Apple's mlx-c (the C API of MLX), generated by bindgen from the pinned
//! headers. MLX and mlx-c are built from source and linked statically; see `build.rs`.
//!
//! Without the `build` feature this crate is empty. Use the safe wrapper, `ollaya-mlx`.

#![cfg(feature = "build")]
// The generated items keep mlx-c's C names (`mlx_array`, `mlx_dtype_`).
#![allow(non_camel_case_types)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Where this build installed `mlx.metallib`. Development builds fall back to it; an installed
/// Ollaya uses the copy in its library directory instead.
pub const BUILD_METALLIB: &str = env!("OLLAYA_MLX_BUILD_METALLIB");
